config {
    type: "table",
    schema: `marts_dataform_${dataform.projectConfig.vars.env}`,
    description: "Mart table for yellow taxi trips aggregated by pickup district",
    assertions: {
       rowConditions: [
            "trips_count >= 0"
       ]
    },
}

with tripdata_details as (
    select * from ${ ref("int_staging__yellow_tripdata_details") }
),

trips_by_district as (
    select pickup_district, count(*) as trips_count
    from tripdata_details
    group by pickup_district
)

select pickup_district, trips_count from trips_by_district